name: Update Readme

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests svgwrite

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Run the script
        env:
          GH_PRIVATE_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
          GH_OWNER: ${{ secrets.GH_OWNER }}
        run: |
          python update.py

      - name: Commit generated files
        run: |
          git config --local user.email "shaileshsaravanan385@gmail.com"
          git config --local user.name "Shailesh Saravanan"
          git add .
          git commit -m "Update generated files" || echo "No changes to commit"
          git push
        env:
          GH_PRIVATE_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
